### ISSUE TITLE
Please reupload the video

### ISSUE THREAD

**Issue by SocksAndStuff** [GTekSD/BurpSuitePro-1.7.37-and-2022.8.5-Cracked#3]
'-noverify' is not recognized as an internal or external command,
operable program or batch file.  

The video is gone and instructions are unclear. Please reupload video before this gets purged

**Comment by GTekSD** [comment]
Alright, i will make a video on it, and will show everything like,
how to activate Burpsuite pro on windows and linux
how to create a shortcut in linux and windows
how to add it into start menu in linux
how to run burpsuite pro with cmd.

because of busy schedule in work please allow me some time.

thank u :)

**Comment by SocksAndStuff** [comment]
Wow I didnt expect you to respond so quickly, but thanks man. I actually figured it out thanks to another version I found. But always happy to have another option. 

Take care and have a wonderful day my man.

**Comment by GTekSD** [comment]
I'm glad to hear that you were able to figure things out and found another solution! I'm here to help whenever you need it, and I appreciate your understanding. Your kind words mean a lot, and I'm committed to assisting the community to the best of my abilities.

Thanks for your support and encouragement. If you ever have more questions or need assistance in the future, don't hesitate to reach out. Take care, and I wish you a fantastic day too, my friend!
